# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for PWARM Physics Engine Demo."""

a = Analysis(
    ['scripts/demo_physics_engine.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'scipy',
        'scipy.spatial',
        'scipy.spatial.KDTree',
        'numpy',
        'pymo.physics',
        'pymo.physics.core',
        'pymo.physics.solvers',
        'pymo.physics.coupling',
        'pymo.physics.collision',
        'pymo.physics.integrator',
        'pymo.physics.ai',
        'pymo.interface',
        'pymo.ai',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PIL',
        'tkinter',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'IPython',
        'jupyter',
        'notebook',
        'torch',
        'tensorflow',
        'pyvista',
        'vtkmodules',
        'matplotlib',
        'setuptools._vendor.jaraco',
        'setuptools._vendor.backports',
        'setuptools._vendor.wheel',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PWARM_PhysicsEngine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
